sudo: required
language: c
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - sudo apt-get install postgresql-server-dev-9.4
  - sudo apt-get install postgresql-common
script:
  - make && sudo make install && make installcheck
